# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kehongying/OS2020_project1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kehongying/OS2020_project1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kehongying/OS2020_project1/CMakeFiles /home/kehongying/OS2020_project1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kehongying/OS2020_project1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project_1

# Build rule for target.
project_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_1
.PHONY : project_1

# fast build rule for target.
project_1/fast:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/build
.PHONY : project_1/fast

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/main.c.s
.PHONY : main.c.s

priority_queue.o: priority_queue.c.o

.PHONY : priority_queue.o

# target to build an object file
priority_queue.c.o:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/priority_queue.c.o
.PHONY : priority_queue.c.o

priority_queue.i: priority_queue.c.i

.PHONY : priority_queue.i

# target to preprocess a source file
priority_queue.c.i:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/priority_queue.c.i
.PHONY : priority_queue.c.i

priority_queue.s: priority_queue.c.s

.PHONY : priority_queue.s

# target to generate assembly for a file
priority_queue.c.s:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/priority_queue.c.s
.PHONY : priority_queue.c.s

process.o: process.c.o

.PHONY : process.o

# target to build an object file
process.c.o:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/process.c.o
.PHONY : process.c.o

process.i: process.c.i

.PHONY : process.i

# target to preprocess a source file
process.c.i:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/process.c.i
.PHONY : process.c.i

process.s: process.c.s

.PHONY : process.s

# target to generate assembly for a file
process.c.s:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/process.c.s
.PHONY : process.c.s

scheduler.o: scheduler.c.o

.PHONY : scheduler.o

# target to build an object file
scheduler.c.o:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/scheduler.c.o
.PHONY : scheduler.c.o

scheduler.i: scheduler.c.i

.PHONY : scheduler.i

# target to preprocess a source file
scheduler.c.i:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/scheduler.c.i
.PHONY : scheduler.c.i

scheduler.s: scheduler.c.s

.PHONY : scheduler.s

# target to generate assembly for a file
scheduler.c.s:
	$(MAKE) -f CMakeFiles/project_1.dir/build.make CMakeFiles/project_1.dir/scheduler.c.s
.PHONY : scheduler.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... project_1"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... priority_queue.o"
	@echo "... priority_queue.i"
	@echo "... priority_queue.s"
	@echo "... process.o"
	@echo "... process.i"
	@echo "... process.s"
	@echo "... scheduler.o"
	@echo "... scheduler.i"
	@echo "... scheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

